# This is a placeholder formula.
# The real formula will be auto-generated by the update-formula workflow
# after the first PyPI release of summon-claude.
#
# To generate manually:
#   pip install homebrew-pypi-poet summon-claude
#   poet -f summon-claude > Formula/summon-claude.rb
#
# Or trigger the workflow:
#   gh workflow run update-formula.yaml -R wgordon17/homebrew-summon

class SummonClaude < Formula
  include Language::Python::Virtualenv

  desc "Bridge Claude Code sessions to Slack channels"
  homepage "https://github.com/wgordon17/summon-claude"
  # url and sha256 will be populated by homebrew-pypi-poet after first PyPI release

  depends_on "python@3.12"

  # Resource blocks will be auto-generated by poet

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "summon, version", shell_output("#{bin}/summon version")
  end
end
