# Placeholder formula — the real formula will be generated by the
# update-formula workflow after the first PyPI release.
#
# To generate manually:
#   pip install homebrew-pypi-poet summon-claude
#   poet -f summon-claude > Formula/summon-claude.rb

class SummonClaude < Formula
  include Language::Python::Virtualenv

  desc "Bridge Claude Code sessions to Slack channels"
  homepage "https://github.com/wgordon17/summon-claude"
  # url and sha256 will be populated after first PyPI release

  depends_on "python@3.12"

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "summon, version", shell_output("#{bin}/summon version")
  end
end
